### PR TITLE
Updates

### PR DESCRIPTION
**Pull request by GrantBirki**
# Updates 🚀 

This pull request changes the following:

- Add news page rules to support greater caching with cloudflare
- Changes our zone from `free` to `pro`
- Re-enables HTTP3
- Enables `webp` and `polish` settings for image optimization

### CODE REVIEW

**Comment by GrantBirki** [comment]
`.deploy` and `.deploy noop` should both return no results as I have already applied the changes with Terraform locally to ensure they work

**Comment by GrantBirki** [comment]
.deploy noop

**Comment by GrantBirki** [comment]
.deploy noop

**Review by thaddeus — APPROVED** [review]

**Comment by GrantBirki** [comment]
.deploy

**Pull request merged**
