### PR TITLE
Branch Deployment Example

### PR DESCRIPTION
**Pull request by GrantBirki**
# Branch Deployment Example

This pull request demonstrates the _branch deployment_ workflow using GitHub Actions, Terraform, and IssueOps

Follow along 👀  with the comments on this PR to see how this works!

### CODE REVIEW

**Comment by GrantBirki** [comment]
I have reviewed the Terraform plan output above ^ and have confirmed it looks correct. At this point would ask for an approval from a member of the [the-hideout reviewer team](https://github.com/orgs/the-hideout/teams/reviewers/members). Let's get this PR approved so I can deploy my changes!

**Review by Blightbuster — APPROVED** [review]
Looks like a good example to me, approved!

**Comment by GrantBirki** [comment]
.deploy

**Comment by GrantBirki** [comment]
Woohoo! 🎉 Looking at an online dig, we can see our DNS record updated exactly as we wanted it too and it is being proxied through Cloudflare.

Screenshot from 2022-04-05 08-37-13

Now that we have confirmed our changes are valid and live in production we can go ahead and merge our PR. Since these changes are already live and their state is reflected in Terraform, the deploy on merge should be a noop which is exactly what we want in this case. Let's 🚢 it!

> Note: If anything went wrong during our deployment, we can always run `.deploy main` (the main branch) to roll back our changes

**Pull request merged**
