### PR TITLE
Security Headers

### PR DESCRIPTION
**Pull request by GrantBirki**
# Security Headers 🔒 

This pull request adds security headers for tarkov.dev in production via cloudflare response modifications

This should improve our ratings on https://observatory.mozilla.org/analyze/tarkov.dev

### CODE REVIEW

**Comment by GrantBirki** [comment]
.deploy

**Comment by GrantBirki** [comment]
.deploy

**Comment by GrantBirki** [comment]
.deploy

**Comment by GrantBirki** [comment]
.deploy

**Comment by GrantBirki** [comment]
.deploy

**Review by Razzmatazzz — APPROVED** [review]

**Pull request merged**
